routes/web.php
		Route::post('/create', ['as'=>'store','uses'=>'ChefController@store']);
		Route::get('/edit/{id}', ['as'=>'edit','uses'=>'ChefController@edit']);
		Route::post('/edit/{id}', ['as'=>'update','uses'=>'ChefController@update']);
		Route::post('/delete/{id}', ['as'=>'delete','uses'=>'ChefController@delete']);
		Route::get('/export', ['as'=>'export','uses'=>'ChefController@export']);
	});

	//Consumers
	Route::group(['prefix' => 'consumers', 'as' => 'consumers.'], function () {
		Route::get('/', ['as'=>'index','uses'=>'ConsumerController@index']);
		Route::get('/create', ['as'=>'create','uses'=>'ConsumerController@create']);
		Route::post('/create', ['as'=>'store','uses'=>'ConsumerController@store']);
		Route::get('/edit/{id}', ['as'=>'edit','uses'=>'ConsumerController@edit']);
		Route::post('/edit/{id}', ['as'=>'update','uses'=>'ConsumerController@update']);
		Route::post('/delete/{id}', ['as'=>'delete','uses'=>'ConsumerController@delete']);
	});

	//Kitchen areas
	Route::group(['prefix' => 'kitchen-areas', 'as' => 'kitchen-areas.'], function () {
		Route::get('/', ['as'=>'index','uses'=>'KitchenAreaController@index']);
		Route::get('/create', ['as'=>'create','uses'=>'KitchenAreaController@create']);
		Route::post('/create', ['as'=>'store','uses'=>'KitchenAreaController@store']);
		Route::get('/edit/{id}', ['as'=>'edit','uses'=>'KitchenAreaController@edit']);
		Route::post('/edit/{id}', ['as'=>'update','uses'=>'KitchenAreaController@update']);
	});

	//Kitchens
	Route::group(['prefix' => 'kitchens', 'as' => 'kitchens.'], function () {
		Route::get('/', ['as'=>'index','uses'=>'KitchenController@index']);
		Route::get('/create', ['as'=>'create','uses'=>'KitchenController@create']);
		Route::post('/create', ['as'=>'store','uses'=>'KitchenController@store'])->middleware('optimizeImages');
		Route::get('/edit/{id}', ['as'=>'edit','uses'=>'KitchenController@edit'])->middleware('optimizeImages');
		Route::post('/edit/{id}', ['as'=>'update','uses'=>'KitchenController@update']);
	});

	//Menus
	Route::group(['prefix' => 'menus', 'as' => 'menus.'], function () {
		Route::get('/', ['as'=>'index','uses'=>'MenuController@index']);
		Route::get('/create', ['as'=>'create','uses'=>'MenuController@create']);
		Route::post('/create', ['as'=>'store','uses'=>'MenuController@store']);
		Route::get('/edit/{id}', ['as'=>'edit','uses'=>'MenuController@edit']);
		Route::post('/edit/{id}', ['as'=>'update','uses'=>'MenuController@update']);
		Route::post('/delete/{id}', ['as'=>'delete','uses'=>'MenuController@delete']);
		Route::post('/approval/{id}', ['as'=>'approval','uses'=>'MenuController@approval']);
	});

	//Menu Settings
	Route::group(['prefix' => 'menu-settings', 'as' => 'menu-settings.'], function () {
		Route::get('/{menu_id}', ['as'=>'index','uses'=>'MenuSettingController@index']);
		Route::get('/create/{menu_id}', ['as'=>'create','uses'=>'MenuSettingController@create']);
		Route::post('/create/{menu_id}', ['as'=>'store','uses'=>'MenuSettingController@store'])->middleware('optimizeImages');
		Route::get('/edit/{id}', ['as'=>'edit','uses'=>'MenuSettingController@edit']);
		Route::post('/edit/{id}', ['as'=>'update','uses'=>'MenuSettingController@update'])->middleware('optimizeImages');
		Route::post('/delete/{id}', ['as'=>'delete','uses'=>'MenuSettingController@delete']);
	});

	//Menu Setting Items
	Route::group(['prefix' => 'menu-setting-items', 'as' => 'menu-setting-items.'], function () {
		Route::get('/{menu_setting_id}', ['as'=>'index','uses'=>'MenuSettingItemController@index']);
		Route::get('/create/{menu_setting_id}', ['as'=>'create','uses'=>'MenuSettingItemController@create']);
		Route::post('/create/{menu_setting_id}', ['as'=>'store','uses'=>'MenuSettingItemController@store'])->middleware('optimizeImages');
		Route::get('/edit/{id}', ['as'=>'edit','uses'=>'MenuSettingItemController@edit']);
		Route::post('/edit/{id}', ['as'=>'update','uses'=>'MenuSettingItemController@update'])->middleware('optimizeImages');
		Route::post('/delete/{id}', ['as'=>'delete','uses'=>'MenuSettingItemController@delete']);
	});

	//Menu Setting Sub Items
	Route::group(['prefix' => 'menu-setting-sub-items', 'as' => 'menu-setting-sub-items.'], function () {
		Route::get('/{menu_setting_item_id}', ['as'=>'index','uses'=>'MenuSettingSubItemController@index']);
		Route::get('/create/{menu_setting_item_id}', ['as'=>'create','uses'=>'MenuSettingSubItemController@create']);
		Route::post('/create/{menu_setting_item_id}', ['as'=>'store','uses'=>'MenuSettingSubItemController@store']);
		Route::get('/edit/{id}', ['as'=>'edit','uses'=>'MenuSettingSubItemController@edit']);
		Route::post('/edit/{id}', ['as'=>'update','uses'=>'MenuSettingSubItemController@update']);
		Route::post('/delete/{id}', ['as'=>'delete','uses'=>'MenuSettingSubItemController@delete']);
	});

	//Menu Setting Secondary Sub Items
	Route::group(['prefix' => 'menu-setting-secondary-sub-items', 'as' => 'menu-setting-secondary-sub-items.'], function () {
		Route::get('/{menu_setting_sub_item_id}', ['as'=>'index','uses'=>'MenuSettingSecondarySubItemController@index']);
		Route::get('/create/{menu_setting_sub_item_id}', ['as'=>'create','uses'=>'MenuSettingSecondarySubItemController@create']);
		Route::post('/create/{menu_setting_sub_item_id}', ['as'=>'store','uses'=>'MenuSettingSecondarySubItemController@store']);
		Route::get('/edit/{id}', ['as'=>'edit','uses'=>'MenuSettingSecondarySubItemController@edit']);
		Route::post('/edit/{id}', ['as'=>'update','uses'=>'MenuSettingSecondarySubItemController@update']);
		Route::post('/delete/{id}', ['as'=>'delete','uses'=>'MenuSettingSecondarySubItemController@delete']);
	});

	//Bookings
	Route::group(['prefix' => 'bookings', 'as' => 'bookings.'], function () {
		Route::get('/', ['as'=>'index','uses'=>'BookingController@index']);
		Route::get('/calendar', ['as'=>'calendar','uses'=>'BookingController@calendar']);
		Route::get('/edit/{id}', ['as'=>'edit','uses'=>'BookingController@edit']);
		Route::post('/edit/{id}', ['as'=>'update','uses'=>'BookingController@update']);
		Route::get('/pdf-receipt/{id}', ['as'=>'createPDF','uses'=>'BookingController@createPDF']);
	});

	//Orders
	Route::group(['prefix' => 'orders', 'as' => 'orders.'], function () {
		Route::get('/', ['as'=>'index','uses'=>'OrderController@index']);
		Route::get('/calendar', ['as'=>'calendar','uses'=>'OrderController@calendar']);
		Route::get('/edit/{id}', ['as'=>'edit','uses'=>'OrderController@edit']);
		Route::post('/edit/{id}', ['as'=>'update','uses'=>'OrderController@update']);
		Route::post('/updateStatus/{id}', ['as'=>'updateStatus','uses'=>'OrderController@updateStatus']);
		Route::post('/refund/{id}', ['as'=>'refund','uses'=>'OrderController@refund']);
	});

	//Order Details
	Route::group(['prefix' => 'order-details', 'as' => 'order-details.'], function () {
		Route::post('/edit', ['as'=>'update','uses'=>'OrderDetailController@update']);
	});

	//Reviews
	Route::group(['prefix' => 'reviews', 'as' => 'reviews.'], function () {
		Route::get('/', ['as'=>'index','uses'=>'ReviewController@index']);
		Route::post('/approval/{id}', ['as'=>'approval','uses'=>'ReviewController@approval']);
		Route::get('/edit/{id}', ['as'=>'edit','uses'=>'ReviewController@edit']);
		Route::post('/edit/{id}', ['as'=>'update','uses'=>'ReviewController@update']);
	});

	//fullcalender
	Route::group(['prefix' => 'fullcalendar', 'as' => 'fullcalendar.'], function () {
		Route::get('/', ['as'=>'index','uses'=>'FullCalendarController@index']);
		Route::get('/create', ['as'=>'create','uses'=>'FullCalendarController@create']);
		Route::post('/update', ['as'=>'update','uses'=>'FullCalendarController@update']);
		Route::get('/delete', ['as'=>'delete','uses'=>'FullCalendarController@delete']);
	});

	//Banners
	Route::group(['prefix' => 'banners', 'as' => 'banners.'], function () {
		Route::get('/', ['as'=>'index','uses'=>'BannerController@index']);
		Route::get('/create', ['as'=>'create','uses'=>'BannerController@create']);
		Route::post('/create', ['as'=>'store','uses'=>'BannerController@store'])->middleware('optimizeImages');
		Route::get('/edit/{id}', ['as'=>'edit','uses'=>'BannerController@edit'])->middleware('optimizeImages');
		Route::post('/edit/{id}', ['as'=>'update','uses'=>'BannerController@update']);
		Route::post('/delete/{id}', ['as'=>'delete','uses'=>'BannerController@delete']);
	});

	//Pictures
	Route::group(['prefix' => 'pictures', 'as' => 'pictures.'], function () {
		Route::get('/', ['as'=>'index','uses'=>'PictureController@index']);
		Route::get('/create', ['as'=>'create','uses'=>'PictureController@create']);
		Route::post('/create', ['as'=>'store','uses'=>'PictureController@store'])->middleware('optimizeImages');
		Route::get('/edit/{id}', ['as'=>'edit','uses'=>'PictureController@edit'])->middleware('optimizeImages');
		Route::post('/edit/{id}', ['as'=>'update','uses'=>'PictureController@update']);
		Route::post('/delete/{id}', ['as'=>'delete','uses'=>'PictureController@delete']);
	});

	//Promotions
	Route::group(['prefix' => 'promotions', 'as' => 'promotions.'], function () {
		Route::get('/', ['as'=>'index','uses'=>'PromotionController@index']);
		Route::get('/create', ['as'=>'create','uses'=>'PromotionController@create']);
		Route::post('/create', ['as'=>'store','uses'=>'PromotionController@store']);
		Route::get('/edit/{id}', ['as'=>'edit','uses'=>'PromotionController@edit']);
		Route::post('/edit/{id}', ['as'=>'update','uses'=>'PromotionController@update']);
		Route::post('/delete/{id}', ['as'=>'delete','uses'=>'PromotionController@delete']);
	});

	//Promo Codes
	Route::group(['prefix' => 'promo-codes', 'as' => 'promo-codes.'], function () {
		Route::get('/', ['as'=>'index','uses'=>'PromoCodeController@index']);
		Route::get('/create', ['as'=>'create','uses'=>'PromoCodeController@create']);
		Route::post('/create', ['as'=>'store','uses'=>'PromoCodeController@store']);
		Route::get('/edit/{id}', ['as'=>'edit','uses'=>'PromoCodeController@edit']);

resources/views/dashboard/menus/settings/items/sub-items/create.blade.php
@extends('layouts.dashboard')

@section('content')
<div class="container-fluid">
	<h1 class="mt-4">Dashboard</h1>
	<ol class="breadcrumb mb-4">
		<li class="breadcrumb-item"><a href="{{ route('home') }}">Dashboard</a></li>
		<li class="breadcrumb-item"><a href="{{ route('menu-setting-sub-items.index',$menu_setting_item->id) }}">Menu Setting Sub Items</a></li>
		<li class="breadcrumb-item active">Create Setting Sub-Item ({{ $menu_setting_item->menuSetting->name }} - {{ $menu_setting_item->name }})</li>
	</ol>
	
	<div class="card mb-4">
		<div class="card-header"><i class="fas fa-table mr-1"></i>Create Setting Sub-Item ({{ $menu_setting_item->menuSetting->name }} - {{ $menu_setting_item->name }})</div>
		@if (session('message'))
			<div class="alert {{ Session::get('alert-class') }}">{{ session('message') }}</div>
		@endif
		@if (count($errors) > 0)
			<div class="alert alert-danger">
				<strong>Whoops!</strong> There were some problems with your input.<br><br>
				<ul>
				   @foreach ($errors->all() as $error)
					 <li>{{ $error }}</li>
				   @endforeach
				</ul>
			</div>
		@endif
		<div class="card-body">
			<form action="{{ route('menu-setting-sub-items.create',$menu_setting_item->id) }}" method="POST" enctype="multipart/form-data">
				@csrf
				<div class="form-group">
					<label for="name">Name: *</label>
					<input type="text" class="form-control" id="name" name="name" value="{{ old('name') }}" required>
				</div>
				
				<div class="form-group">
					<label for="description">Price: </label>
					<input type="number" placeholder="Enter item price" class="form-control" id="price" name="price" step="0.01">
				</div>
				<button type="submit" class="btn btn-primary">Submit</button>
			</form>
		</div>
	</div>
</div>         
@endsection

resources/views/dashboard/menus/settings/items/sub-items/edit.blade.php
@extends('layouts.dashboard')

@section('content')
<div class="container-fluid">
	<h1 class="mt-4">Dashboard</h1>
	<ol class="breadcrumb mb-4">
		<li class="breadcrumb-item"><a href="{{ route('home') }}">Dashboard</a></li>
		<li class="breadcrumb-item"><a href="{{ route('menu-setting-sub-items.index',$menu_setting_item->id) }}">Menu Setting Sub Items</a></li>
		<li class="breadcrumb-item active">Edit Setting Sub-Item ({{ $menu_setting_item->name }} - {{ $menu_setting_item->name }} - {{ $data->name }})</li>
	</ol>
	
	<div class="card mb-4">
		<div class="card-header"><i class="fas fa-table mr-1"></i>Edit Setting Sub-Item ({{ $menu_setting_item->name }} - {{ $menu_setting_item->name }} - {{ $data->name }})</div>
		@if (session('message'))
			<div class="alert {{ Session::get('alert-class') }}">{{ session('message') }}</div>
		@endif
		@if (count($errors) > 0)
			<div class="alert alert-danger">
				<strong>Whoops!</strong> There were some problems with your input.<br><br>
				<ul>
				   @foreach ($errors->all() as $error)
					 <li>{{ $error }}</li>
				   @endforeach
				</ul>
			</div>
		@endif
		<div class="card-body">
			<form action="{{ route('menu-setting-sub-items.edit',$data->id) }}" method="POST" enctype="multipart/form-data">
				@csrf
				<div class="form-group">
					<label for="name">Name: *</label>
					<input type="text" class="form-control" id="name" name="name" value="{{ old('name',$data->name) }}" required>
				</div>
				
				<div class="form-group">
					<label for="description">Price: </label>
					<input type="number" placeholder="Enter item price" class="form-control" id="price" name="price" step="0.01" value="{{ old('name',$data->price) }}">
				</div>
				<button type="submit" class="btn btn-primary">Submit</button>
			</form>
		</div>
	</div>
</div>         
@endsection

resources/views/dashboard/menus/settings/items/sub-items/index.blade.php
@extends('layouts.dashboard')

@section('content')
<div class="container-fluid">
	<h1 class="mt-4">Dashboard</h1>
	<ol class="breadcrumb mb-4">
		<li class="breadcrumb-item"><a href="{{ route('home') }}">Dashboard</a></li>
		<li class="breadcrumb-item"><a href="{{ route('menu-setting-items.index',$menu_setting_item->menuSetting->id) }}">Menu Setting Items</a></li>
		<li class="breadcrumb-item active">Menu Setting Sub-Items ({{ $menu_setting_item->menuSetting->name }} - {{ $menu_setting_item->name }})</li>
	</ol>
	
	<div class="card mb-4">
		<div class="card-header"><i class="fas fa-table mr-1"></i>Menu Setting Sub-Items ({{ $menu_setting_item->menuSetting->name }} - {{ $menu_setting_item->name }})</div>
		@if (session('message'))
			<div class="alert {{ Session::get('alert-class') }}">{{ session('message') }}</div>
		@endif
		<div class="card-body">
			<a href="{{ route('menu-setting-sub-items.create',$menu_setting_item->id) }}" class="btn btn-primary float-right">Add</a>
		</div>
		<div class="card-body">
			<table class="table">
				<thead>
					<tr>
						<th width="20%">Name</th>
						<th width="20%">Price</th>
						<th width="20%">Created At</th>
						<th width="20%"></th>
					</tr>
				</thead>
				<tbody>
				@foreach($data as $value)
					<tr>
						<td>{{ $value->name }}</td>
						<td>{{ $value->price }}</td>
						<td>{{ $value->created_at }}</td>
						<td>
							<div class="dropdown">
								<button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
									Action
								</button>
								<div class="dropdown-menu">
									<a class="dropdown-item" href="{{ route('menu-setting-sub-items.edit', $value->id) }}">Edit</a>
									<a class="dropdown-item" href="{{ route('menu-setting-secondary-sub-items.index', $value->id) }}">View Sec-Sub-Items</a>
									<a class="dropdown-item" href="#" data-toggle="modal" data-target="#deleteModal_{{ $value->id }}">Delete</a>
								</div>
							</div>
						</td>
					</tr>
					<div class="modal fade" id="deleteModal_{{ $value->id }}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
						<div class="modal-dialog" role="document">
						  <div class="modal-content">
							<div class="modal-header">
							  <h5 class="modal-title" id="exampleModalLabel">Delete Record?</h5>
							  <button class="close" type="button" data-dismiss="modal" aria-label="Close">
								<span aria-hidden="true">×</span>
							  </button>
							</div>
							<div class="modal-body">Select "Delete" below if you are ready to delete the record.</div>
							<div class="modal-footer">
								<button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
								<form id="delete-form" action="{{ route('menu-setting-sub-items.delete',$value->id) }}" method="POST" style="display: none;">
									@csrf
									<button type="submit" class="btn btn-danger">Delete</button>
								</form>
							</div>
						  </div>
						</div>
					</div>
				@endforeach
				</tbody>
			</table>
		</div>
		{!!$data->appends(Request::only('keyword'))->links() !!}
	</div>
</div>
                
@endsection